server:
  port: 3000
spring:
  profiles:
    active: local
  jmx:
    enabled: false
  datasource:
    url: jdbc:h2:mem:bookdb
    driver-class-name: org.h2.Driver
    username: book
    password: book
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  jackson:
    serialization:
      indent_output: true
  security:
    basic:
      enabled: false
logging:
  level:
    io.mike.api: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE